### ISSUE TITLE
Multiple dependencies support

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#41]
Umbrella issue for multiple dependencies support in ZeppelinOS.

- [x] Update lib contracts
- [x] Update lib models
- [x] Update lib examples
- [x] Update CLI main commands
- [ ] Update documentation
- [x] Add CLI command to remove a dependency
- [x] Update stdlib model tests
- [x] Update TestApp model to work with new Projects
- [x] Update CLI status check
- [x] Update CLI status fetch and pull
- [ ] Validate CLI json version
- [ ] (optional) Auto upgrade from CLI previous json format

**Comment by facuspagnuolo** [comment]
Closing this issue, documentation items will be tackled in https://github.com/zeppelinos/zos-docs/issues/93
