### ISSUE TITLE
Lay out a general migration plan to typescript

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#434]
Consider the following tasks:

- Dependency management in monorepo
- Tests via truffle or plain mocha
- Build for releases
- Adding typings for dependencies
- Typings for contracts
- Order of tsconfig checks
- Order of classes to convert into ts
- Linters

**Comment by ajsantander** [comment]
# Typescript migration plan

This document outlines a general plan for migrating ZeppelinOS to Typescript. The steps don't need to be followed _to the letter_, but they lay out a tempting path to use as a backbone for the migration. 

## Guidelines

The following guidelines should be taken into consideration in all phases during porting.

### File port order

Files that have less dependencies should be ported first. This defines a porting tree that is traversed from leaf to branch, to the main trunk of the tree. To help identify and visualize the dependency tree Webstorm's UML diagrams feature can be used, as well as the madge NPM package, which can be used as follows:

`madge packages/lib/src --exclude ../lib --summary`

## Phases

The migration is divided into the following set of phases. Tasks within a phase can be parallelized, but a new phase should not be started until the previous one is completed.

### Phase 0: Bootstrapping

This phase involves bootstrapping Typescript into the project, so that the migration process can begin.

- [x] Design a POC of how TS could be integrated into the project. => https://github.com/zeppelinos/zos/pull/443
- [x] Setup a global linter for the entire project.
- [ ] Bootstrap TS into the project and officially begin the migration. => Merge 443
- [ ] Define initial set of linting rules in `tslint.json`.
- [ ] Activate source maps and define a debugging workflow.

### Phase 1: Syntax port of src folders

This phases involves porting all `.js` files to `.ts` files contained within the `src` folders, following the suggested file port order from the guidelines above. Note that in this phase we are not paying particular attention to OOP design patterns, but merely porting the Javascript syntax to Typescript syntax. At the end of this phase, there should be no `.js` files in any of the packages' `src` folders. The following tasklist shows all files, ordered by number of dependencies, by package.

- [ ] packages/lib/src
<details>
<summary>(click to expand sub-tasks)</summary>

  - [ ] 0 utils/Bytecode.js
  - [ ] 0 test/helpers/assertEvent.js
  - [ ] 0 test/helpers/assertRevert.js
  - [ ] 0 utils/Contracts.js
  - [ ] 0 utils/FileSystem.js
  - [ ] 0 utils/Logger.js
  - [ ] 0 utils/Semver.js
  - [ ] 0 utils/Solidity.js
  - [ ] 0 helpers/encodeCall.js
  - [ ] 0 utils/errors/DeployError.js
  - [ ] 0 validations/Constructors.js
  - [ ] 0 helpers/advanceBlock.js
  - [ ] 0 helpers/decodeLogs.js
  - [ ] 0 utils/Addresses.js
  - [ ] 0 validations/Layout.js
  - [ ] 0 helpers/sleep.js
  - [ ] 1 test/behaviors/Ownable.js
  - [ ] 1 test/helpers/assertions.js
  - [ ] 1 index.js
  - [ ] 1 utils/ContractAST.js
  - [ ] 1 validations/Storage.js
  - [ ] 1 validations/InitialValues.js
  - [ ] 1 validations/Initializers.js
  - [ ] 1 validations/Instructions.js
  - [ ] 2 utils/BuildArtifacts.js
  - [ ] 2 utils/ABIs.js
  - [ ] 2 utils/Transactions.js
  - [ ] 3 helpers/copyContract.js
  - [ ] 3 proxy/Proxy.js
  - [ ] 3 directory/ImplementationDirectory.js
  - [ ] 3 project/BasePackageProject.js
  - [ ] 4 test/index.js
  - [ ] 4 project/LibProject.js
  - [ ] 5 project/AppProject.js
  - [ ] 6 project/SimpleProject.js
  - [ ] 6 package/Package.js
  - [ ] 7 validations/index.js
  - [ ] 9 app/App.js
</details>

&nbsp;
- [ ] packages/cli/src
<details>
<summary>(click to expand sub-tasks)</summary>

  - [ ] 0 models/truffle/Truffle.js
  - [ ] 0 models/truffle/blueprint.truffle.js
  - [ ] 0 models/files/ZosVersion.js
  - [ ] 0 models/network/ProjectDeployer.js
  - [ ] 0 models/network/Session.js
  - [ ] 0 models/errors/ErrorHandler.js
  - [ ] 0 models/status/EventsFilter.js
  - [ ] 0 models/errors/ScriptError.js
  - [ ] 0 interface/ValidationLogger.js
  - [ ] 0 models/status/StatusFetcher.js
  - [ ] 0 utils/async.js
  - [ ] 0 utils/input.js
  - [ ] 0 utils/naming.js
  - [ ] 0 utils/promptBoolean.js
  - [ ] 0 models/status/StatusReport.js
  - [ ] 0 utils/sleep.js
  - [ ] 0 utils/stdout.js
  - [ ] 1 scripts/compare.js
  - [ ] 1 scripts/add.js
  - [ ] 1 scripts/add-all.js
  - [ ] 1 models/status/StatusComparator.js
  - [ ] 1 bin/errors.js
  - [ ] 1 bin/options.js
  - [ ] 1 models/Verifier.js
  - [ ] 1 scripts/check.js
  - [ ] 1 scripts/remove.js
  - [ ] 1 scripts/session.js
  - [ ] 1 index.js
  - [ ] 1 scripts/status.js
  - [ ] 1 commands/session.js
  - [ ] 1 bin/zos-cli.js
  - [ ] 1 scripts/verify.js
  - [ ] 1 models/TestHelper.js
  - [ ] 2 commands/init.js
  - [ ] 2 scripts/pull.js
  - [ ] 2 models/dependency/Dependency.js
  - [ ] 2 models/files/ZosNetworkFile.js
  - [ ] 2 commands/link.js
  - [ ] 2 commands/publish.js
  - [ ] 2 commands/push.js
  - [ ] 2 commands/remove.js
  - [ ] 2 scripts/unlink.js
  - [ ] 2 scripts/publish.js
  - [ ] 2 commands/check.js
  - [ ] 2 models/network/ControllerFor.js
  - [ ] 2 utils/runWithTruffle.js
  - [ ] 2 scripts/link.js
  - [ ] 2 models/network/NetworkLibController.js
  - [ ] 2 commands/unlink.js
  - [ ] 2 commands/freeze.js
  - [ ] 2 scripts/init.js
  - [ ] 2 scripts/init-lib.js
  - [ ] 2 commands/verify.js
  - [ ] 2 scripts/bump.js
  - [ ] 2 scripts/freeze.js
  - [ ] 2 commands/bump.js
  - [ ] 2 models/local/LocalLibController.js
  - [ ] 3 bin/program.js
  - [ ] 3 models/files/index.js
  - [ ] 3 models/local/ControllerFor.js
  - [ ] 3 models/local/LocalAppController.js
  - [ ] 3 commands/set-admin.js
  - [ ] 3 scripts/update.js
  - [ ] 3 scripts/create.js
  - [ ] 3 scripts/set-admin.js
  - [ ] 3 models/status/StatusChecker.js
  - [ ] 3 scripts/push.js
  - [ ] 3 models/files/ZosPackageFile.js
  - [ ] 4 models/network/NetworkBaseController.js
  - [ ] 4 commands/status.js
  - [ ] 4 commands/add.js
  - [ ] 4 models/local/LocalBaseController.js
  - [ ] 4 models/local/index.js
  - [ ] 4 commands/create.js
  - [ ] 4 models/network/index.js
  - [ ] 4 commands/update.js
  - [ ] 5 models/network/NetworkAppController.js
  - [ ] 16 commands/index.js
  - [ ] 19 scripts/index.js
</details>

&nbsp;
- [ ] packages/vouching/src
<details>
<summary>(click to expand sub-tasks)</summary>

  - [ ] 0 helpers/log.js
  - [ ] 0 helpers/validateAddress.js
  - [ ] 0 kernel/exportKernelData.js
  - [ ] 0 constants.js
  - [ ] 1 kernel/fetchKernelContracts.js
  - [ ] 2 kernel/configureTPL.js
  - [ ] 2 bin/verify.js
  - [ ] 2 kernel/printKernelInformation.js
  - [ ] 2 bin/deploy.js
  - [ ] 4 kernel/createKernelContracts.js
  - [ ] 4 scripts/verify.js
  - [ ] 5 scripts/deploy.js
</details>

&nbsp;
### Phase 2: Export types

As soon as our code starts using types, we should also export `.d.ts` files so that our packages can be used by other Typescript projects. This, of course, could be done at a later phase, but it is included here because some of our packages depend on other packages of ours.

- [ ] Type packages/lib.
- [ ] Ensure all usages of packages/lib in other packages use its types.
- [ ] Type packages/cli.
- [ ] Type packages/vouching.

### Phase 3: Syntax port of test folders

After Truffle has been removed from the testing pipeline, the same process applied to the `src` folders in phase 1 can be applied to the `test` folders.

- [ ] packages/lib/test/src
<details>
<summary>(click to expand sub-tasks)</summary>

   - [ ] 0 ../../src/utils/Semver.js
   - [ ] 1 project/ProxyProject.behaviour.js
   - [ ] 1 ../../src/test/helpers/assertions.js
   - [ ] 1 ../setup.js
   - [ ] 1 app/App.test.js
   - [ ] 1 directory/ImplementationDirectory.test.js
   - [ ] 1 package/Package.test.js
   - [ ] 1 project/AppProject.test.js
   - [ ] 1 project/DependenciesProject.behaviour.js
   - [ ] 1 project/LibProject.test.js
   - [ ] 1 project/PackageProject.behavior.js
   - [ ] 1 validations/Storage.test.js
   - [ ] 1 project/SimpleProject.test.js
   - [ ] 1 utils/ABIs.test.js
   - [ ] 1 utils/Bytecode.test.js
   - [ ] 1 utils/Contracts.test.js
   - [ ] 1 utils/FileSystem.test.js
   - [ ] 1 utils/Transactions.test.js
   - [ ] 1 validations/Layout.test.js
   - [ ] 1 validations/Validations.test.js
</details>

&nbsp;
- [ ] packages/cli/test
<details>
<summary>(click to expand sub-tasks)</summary>

   - [ ] 0 ../src/utils/async.js
   - [ ] 0 mocks/mock-stdlib/truffle.js
   - [ ] 0 mocks/mock-stdlib-unpublished/truffle.js
   - [ ] 0 mocks/mock-stdlib-undeployed/truffle.js
   - [ ] 0 mocks/mock-stdlib-undeployed-2/truffle.js
   - [ ] 0 mocks/mock-stdlib-2/truffle.js
   - [ ] 0 helpers/cleanup.js
   - [ ] 0 helpers/captureLogs.js
   - [ ] 0 ../src/utils/stdout.js
   - [ ] 0 ../src/utils/sleep.js
   - [ ] 0 ../src/utils/naming.js
   - [ ] 0 ../src/utils/input.js
   - [ ] 0 mocks/mock-stdlib-unsupported/truffle.js
   - [ ] 0 ../src/models/truffle/Truffle.js
   - [ ] 0 ../src/models/status/StatusReport.js
   - [ ] 0 ../src/models/status/StatusFetcher.js
   - [ ] 0 ../src/models/status/EventsFilter.js
   - [ ] 0 ../src/models/network/Session.js
   - [ ] 0 ../src/models/network/ProjectDeployer.js
   - [ ] 0 ../src/models/files/ZosVersion.js
   - [ ] 0 ../src/models/errors/ScriptError.js
   - [ ] 0 ../src/models/errors/ErrorHandler.js
   - [ ] 0 ../src/interface/ValidationLogger.js
   - [ ] 0 ../package.json
   - [ ] 1 ../src/scripts/add-all.js
   - [ ] 1 ../src/scripts/add.js
   - [ ] 1 utils/input.test.js
   - [ ] 1 ../src/scripts/check.js
   - [ ] 1 ../src/scripts/compare.js
   - [ ] 1 ../src/models/Verifier.js
   - [ ] 1 scripts/verify.test.js
   - [ ] 1 ../src/commands/session.js
   - [ ] 1 utils/async.test.js
   - [ ] 1 scripts/update.test.js
   - [ ] 1 scripts/unlink.test.js
   - [ ] 1 scripts/status.test.js
   - [ ] 1 utils/naming.test.js
   - [ ] 1 ../src/scripts/remove.js
   - [ ] 1 ../src/scripts/session.js
   - [ ] 1 ../src/models/status/StatusComparator.js
   - [ ] 1 ../src/scripts/status.js
   - [ ] 1 scripts/set-admin.test.js
   - [ ] 1 ../src/bin/errors.js
   - [ ] 1 ../src/scripts/verify.js
   - [ ] 1 scripts/push.test.js
   - [ ] 1 scripts/publish.test.js
   - [ ] 1 scripts/link.test.js
   - [ ] 1 scripts/session.test.js
   - [ ] 1 scripts/init.test.js
   - [ ] 1 scripts/init-lib.test.js
   - [ ] 1 commands/add.test.js
   - [ ] 1 commands/bump.test.js
   - [ ] 1 commands/check.test.js
   - [ ] 1 commands/create.test.js
   - [ ] 1 commands/freeze.test.js
   - [ ] 1 commands/init.test.js
   - [ ] 1 commands/link.test.js
   - [ ] 1 commands/publish.test.js
   - [ ] 1 commands/push.test.js
   - [ ] 1 commands/remove.test.js
   - [ ] 1 commands/session.test.js
   - [ ] 1 commands/setAdmin.test.js
   - [ ] 1 scripts/remove.test.js
   - [ ] 1 commands/status.test.js
   - [ ] 1 commands/unlink.test.js
   - [ ] 1 commands/update.test.js
   - [ ] 1 commands/verify.test.js
   - [ ] 1 scripts/freeze.test.js
   - [ ] 1 scripts/create.test.js
   - [ ] 1 interface/ValidationLogger.test.js
   - [ ] 1 scripts/check.test.js
   - [ ] 1 scripts/bump.test.js
   - [ ] 1 scripts/add.test.js
   - [ ] 1 models/ZosPackageFile.test.js
   - [ ] 1 models/ZosNetworkFile.test.js
   - [ ] 1 models/Truffle.test.js
   - [ ] 1 models/Dependency.test.js
   - [ ] 1 models/StatusComparator.test.js
   - [ ] 1 models/StatusFetcher.test.js
   - [ ] 1 models/TestHelper.test.js
   - [ ] 2 ../src/models/dependency/Dependency.js
   - [ ] 2 ../src/commands/verify.js
   - [ ] 2 ../src/commands/unlink.js
   - [ ] 2 ../src/commands/remove.js
   - [ ] 2 ../src/commands/push.js
   - [ ] 2 ../src/models/local/LocalLibController.js
   - [ ] 2 ../src/models/network/ControllerFor.js
   - [ ] 2 ../src/commands/publish.js
   - [ ] 2 ../src/commands/link.js
   - [ ] 2 ../src/models/network/NetworkLibController.js
   - [ ] 2 ../src/commands/init.js
   - [ ] 2 ../src/models/files/ZosNetworkFile.js
   - [ ] 2 ../src/commands/freeze.js
   - [ ] 2 ../src/scripts/freeze.js
   - [ ] 2 ../src/scripts/init-lib.js
   - [ ] 2 ../src/scripts/init.js
   - [ ] 2 ../src/scripts/link.js
   - [ ] 2 ../src/scripts/publish.js
   - [ ] 2 ../src/scripts/pull.js
   - [ ] 2 ../src/commands/check.js
   - [ ] 2 ../src/commands/bump.js
   - [ ] 2 ../src/scripts/unlink.js
   - [ ] 2 ../src/utils/runWithTruffle.js
   - [ ] 2 ../src/scripts/bump.js
   - [ ] 3 ../src/scripts/push.js
   - [ ] 3 ../src/scripts/update.js
   - [ ] 3 ../src/scripts/create.js
   - [ ] 3 ../src/models/local/LocalAppController.js
   - [ ] 3 ../src/commands/set-admin.js
   - [ ] 3 ../src/scripts/set-admin.js
   - [ ] 3 ../src/bin/program.js
   - [ ] 3 ../src/models/status/StatusChecker.js
   - [ ] 3 ../src/models/files/ZosPackageFile.js
   - [ ] 3 setup.js
   - [ ] 3 ../src/models/local/ControllerFor.js
   - [ ] 4 ../src/commands/add.js
   - [ ] 4 ../src/commands/create.js
   - [ ] 4 ../src/models/network/NetworkBaseController.js
   - [ ] 4 ../src/models/local/LocalBaseController.js
   - [ ] 4 ../src/commands/status.js
   - [ ] 4 ../src/commands/update.js
   - [ ] 5 ../src/models/network/NetworkAppController.js
   - [ ] 16 ../src/commands/index.js
   - [ ] 24 commands/share.js
</details>

&nbsp;
- [ ] packages/vouching/test/src
<details>
<summary>(click to expand sub-tasks)</summary>

   - [ ] 0 ../../src/helpers/validateAddress.js
   - [ ] 0 ../../src/helpers/log.js
   - [ ] 0 ../../src/constants.js
   - [ ] 0 ../../src/kernel/exportKernelData.js
   - [ ] 1 ../../src/kernel/fetchKernelContracts.js
   - [ ] 2 ../../src/kernel/configureTPL.js
   - [ ] 2 ../../src/kernel/printKernelInformation.js
   - [ ] 3 scripts/deploy.test.js
   - [ ] 4 ../../src/kernel/createKernelContracts.js
   - [ ] 4 ../../src/scripts/verify.js
   - [ ] 5 ../../src/scripts/deploy.js
</details>

&nbsp;
### Phase 4: Typed dependencies

This phase involves introducing typings to all the 3rd party dependencies used in the project. More precisely, this involves using Typescript 2.x's @types dependencies so that the compiler understands the types used by the dependencies, instead of it inferring `any` all over the place. This also involves adapting our code to use these types.

- [ ] packages/lib
  - [ ] axios
  - [ ] bignumber.js
  - [ ] chalk
  - [ ] glob
  - [ ] semver
  - [ ] web3
- [ ] packages/cli
  - [ ] axios
  - [ ] chalk
  - [ ] cheerio
  - [ ] commander
  - [ ] lockfile
  - [ ] lodash
  - [ ] npm-programmatic
  - [ ] semver
  - [ ] sinon
  - [ ] web3-provider-engine
- [ ] packages/vouching 
  - [ ] chalk
  - [ ] minimist

### Phase 5: Strict compiler and linter settings

This phase involves enabling stricter Typescript compiler settings and making all the necessary changes in the Typescript files. The documentation for all compiler settings can be found at http://www.typescriptlang.org/docs/handbook/compiler-options.html. The settings should be set in the following order:

#### Compiler settings
- [ ] esModuleInterop: false // Disable compatibility with Babel.
- [ ] checkJs: true // Report errors in `.js` files.
- [ ] alwaysStrict: true // Parse Javascript in strict mode.
- [ ] allowJs: false // Stop allowing `.js` files.
- [ ] noUnusedLocals: true // Report errors on unused locals.
- [ ] noUnusedParameters: true // Report errors on unused parameters.
- [ ] noImplicitReturns: true // Report error when not all code paths in function return a value.
- [ ] noImplicitThis: true // `this.` needs to be typed always.
- [ ] noImplicitAny: true // No inference of the `any` type.
- [ ] strictNullChecks: true // `null` and `undefined` are strict types, to be handled by unions.
- [ ] strictFuncitonTypes: true // Disable bivariant parameter checking for function types.
- [ ] strictPropertyInitialization: true // Ensure non-undefined class properties are initialized in the constructor.
- [ ] noEmitOnError: true // Do not output any Javascript if any error is found.

#### Linter settings
*TBD

### Phase 6: OOP enforcing

In this phase, we can begin focusing on refactors that make the code more OOP designed. This means not just complying to Typescript syntax, but actually architecturing the code around Classes, Interfases, Generics, etc. That is, making the most out of the OOP design patterns that Typescript enables.

*TBD: Define task list of refactors that enforce a more OOP-like architecture. Drawing an in depth UML diagram would help in identifying OOP structures that could be applied.

**Comment by spalladino** [comment]
@ajsantander looks great! A few comments:

- I'd leave the vouching package out of the migration for now, until we are comfortable with lib and cli.
- Same for tests, I'm afraid it would be a huge effort to port them. I'd prefer porting just one test to have as a reference for all future tests, but leave the existing ones in js for now.
- Let's keep an eye on web3x and other typescript web3 libraries, which may be a better idea than just typings to web3.js.

**Comment by ajsantander** [comment]
@spalladino I've updated my previous comment (the plan) with your suggestions. Thank you =D

**Comment by ajsantander** [comment]
## Porting of the cli package

This is the continuation of the migration plan, now focused on the cli package. Please use the migration plan for lib as reference.

### Cli Phase 0: Bootstrapping

- [ ] Bootstrap ts config in cli.
- [ ] Setup tests and remove babel.

### Cli Phase 1: Syntax port of cli.

Idem Phase 1 for lib, but for `packages/cli`.

- [ ] **packages/cli/src**
<details>
<summary>(click to expand sub-tasks)</summary>

  - [ ] 0 models/truffle/Truffle.js
  - [ ] 0 models/truffle/blueprint.truffle.js
  - [ ] 0 models/files/ZosVersion.js
  - [ ] 0 models/network/ProjectDeployer.js
  - [ ] 0 models/network/Session.js
  - [ ] 0 models/errors/ErrorHandler.js
  - [ ] 0 models/status/EventsFilter.js
  - [ ] 0 models/errors/ScriptError.js
  - [ ] 0 interface/ValidationLogger.js
  - [ ] 0 models/status/StatusFetcher.js
  - [ ] 0 utils/async.js
  - [ ] 0 utils/input.js
  - [ ] 0 utils/naming.js
  - [ ] 0 utils/promptBoolean.js
  - [ ] 0 models/status/StatusReport.js
  - [ ] 0 utils/sleep.js
  - [ ] 0 utils/stdout.js
  - [ ] 1 scripts/compare.js
  - [ ] 1 scripts/add.js
  - [ ] 1 scripts/add-all.js
  - [ ] 1 models/status/StatusComparator.js
  - [ ] 1 bin/errors.js
  - [ ] 1 bin/options.js
  - [ ] 1 models/Verifier.js
  - [ ] 1 scripts/check.js
  - [ ] 1 scripts/remove.js
  - [ ] 1 scripts/session.js
  - [ ] 1 index.js
  - [ ] 1 scripts/status.js
  - [ ] 1 commands/session.js
  - [ ] 1 bin/zos-cli.js
  - [ ] 1 scripts/verify.js
  - [ ] 1 models/TestHelper.js
  - [ ] 2 commands/init.js
  - [ ] 2 scripts/pull.js
  - [ ] 2 models/dependency/Dependency.js
  - [ ] 2 models/files/ZosNetworkFile.js
  - [ ] 2 commands/link.js
  - [ ] 2 commands/publish.js
  - [ ] 2 commands/push.js
  - [ ] 2 commands/remove.js
  - [ ] 2 scripts/unlink.js
  - [ ] 2 scripts/publish.js
  - [ ] 2 commands/check.js
  - [ ] 2 models/network/ControllerFor.js
  - [ ] 2 utils/runWithTruffle.js
  - [ ] 2 scripts/link.js
  - [ ] 2 models/network/NetworkLibController.js
  - [ ] 2 commands/unlink.js
  - [ ] 2 commands/freeze.js
  - [ ] 2 scripts/init.js
  - [ ] 2 scripts/init-lib.js
  - [ ] 2 commands/verify.js
  - [ ] 2 scripts/bump.js
  - [ ] 2 scripts/freeze.js
  - [ ] 2 commands/bump.js
  - [ ] 2 models/local/LocalLibController.js
  - [ ] 3 bin/program.js
  - [ ] 3 models/files/index.js
  - [ ] 3 models/local/ControllerFor.js
  - [ ] 3 models/local/LocalAppController.js
  - [ ] 3 commands/set-admin.js
  - [ ] 3 scripts/update.js
  - [ ] 3 scripts/create.js
  - [ ] 3 scripts/set-admin.js
  - [ ] 3 models/status/StatusChecker.js
  - [ ] 3 scripts/push.js
  - [ ] 3 models/files/ZosPackageFile.js
  - [ ] 4 models/network/NetworkBaseController.js
  - [ ] 4 commands/status.js
  - [ ] 4 commands/add.js
  - [ ] 4 models/local/LocalBaseController.js
  - [ ] 4 models/local/index.js
  - [ ] 4 commands/create.js
  - [ ] 4 models/network/index.js
  - [ ] 4 commands/update.js
  - [ ] 5 models/network/NetworkAppController.js
  - [ ] 16 commands/index.js
  - [ ] 19 scripts/index.js
</details>

&nbsp;
### Cli Phase 2: Export declaration files for cli

Idem phase 2 for lib, but for the cli package. 

- [ ] Type packages/cli (package tsconfig.json file, compiler settings `declaration: true`, `allowJs: false`).
- [ ] **(OPTIONAL)** Type packages/vouching.

### Cli Phase 3: Partial syntax port of test folders

- [ ] **packages/cli/test** **(OPTIONAL)**
<details>
<summary>(click to expand sub-tasks)</summary>

   - [ ] 0 ../src/utils/async.js
   - [ ] 0 mocks/mock-stdlib/truffle.js
   - [ ] 0 mocks/mock-stdlib-unpublished/truffle.js
   - [ ] 0 mocks/mock-stdlib-undeployed/truffle.js
   - [ ] 0 mocks/mock-stdlib-undeployed-2/truffle.js
   - [ ] 0 mocks/mock-stdlib-2/truffle.js
   - [ ] 0 helpers/cleanup.js
   - [ ] 0 helpers/captureLogs.js
   - [ ] 0 ../src/utils/stdout.js
   - [ ] 0 ../src/utils/sleep.js
   - [ ] 0 ../src/utils/naming.js
   - [ ] 0 ../src/utils/input.js
   - [ ] 0 mocks/mock-stdlib-unsupported/truffle.js
   - [ ] 0 ../src/models/truffle/Truffle.js
   - [ ] 0 ../src/models/status/StatusReport.js
   - [ ] 0 ../src/models/status/StatusFetcher.js
   - [ ] 0 ../src/models/status/EventsFilter.js
   - [ ] 0 ../src/models/network/Session.js
   - [ ] 0 ../src/models/network/ProjectDeployer.js
   - [ ] 0 ../src/models/files/ZosVersion.js
   - [ ] 0 ../src/models/errors/ScriptError.js
   - [ ] 0 ../src/models/errors/ErrorHandler.js
   - [ ] 0 ../src/interface/ValidationLogger.js
   - [ ] 0 ../package.json
   - [ ] 1 ../src/scripts/add-all.js
   - [ ] 1 ../src/scripts/add.js
   - [ ] 1 utils/input.test.js
   - [ ] 1 ../src/scripts/check.js
   - [ ] 1 ../src/scripts/compare.js
   - [ ] 1 ../src/models/Verifier.js
   - [ ] 1 scripts/verify.test.js
   - [ ] 1 ../src/commands/session.js
   - [ ] 1 utils/async.test.js
   - [ ] 1 scripts/update.test.js
   - [ ] 1 scripts/unlink.test.js
   - [ ] 1 scripts/status.test.js
   - [ ] 1 utils/naming.test.js
   - [ ] 1 ../src/scripts/remove.js
   - [ ] 1 ../src/scripts/session.js
   - [ ] 1 ../src/models/status/StatusComparator.js
   - [ ] 1 ../src/scripts/status.js
   - [ ] 1 scripts/set-admin.test.js
   - [ ] 1 ../src/bin/errors.js
   - [ ] 1 ../src/scripts/verify.js
   - [ ] 1 scripts/push.test.js
   - [ ] 1 scripts/publish.test.js
   - [ ] 1 scripts/link.test.js
   - [ ] 1 scripts/session.test.js
   - [ ] 1 scripts/init.test.js
   - [ ] 1 scripts/init-lib.test.js
   - [ ] 1 commands/add.test.js
   - [ ] 1 commands/bump.test.js
   - [ ] 1 commands/check.test.js
   - [ ] 1 commands/create.test.js
   - [ ] 1 commands/freeze.test.js
   - [ ] 1 commands/init.test.js
   - [ ] 1 commands/link.test.js
   - [ ] 1 commands/publish.test.js
   - [ ] 1 commands/push.test.js
   - [ ] 1 commands/remove.test.js
   - [ ] 1 commands/session.test.js
   - [ ] 1 commands/setAdmin.test.js
   - [ ] 1 scripts/remove.test.js
   - [ ] 1 commands/status.test.js
   - [ ] 1 commands/unlink.test.js
   - [ ] 1 commands/update.test.js
   - [ ] 1 commands/verify.test.js
   - [ ] 1 scripts/freeze.test.js
   - [ ] 1 scripts/create.test.js
   - [ ] 1 interface/ValidationLogger.test.js
   - [ ] 1 scripts/check.test.js
   - [ ] 1 scripts/bump.test.js
   - [ ] 1 scripts/add.test.js
   - [ ] 1 models/ZosPackageFile.test.js
   - [ ] 1 models/ZosNetworkFile.test.js
   - [ ] 1 models/Truffle.test.js
   - [ ] 1 models/Dependency.test.js
   - [ ] 1 models/StatusComparator.test.js
   - [ ] 1 models/StatusFetcher.test.js
   - [ ] 1 models/TestHelper.test.js
   - [ ] 2 ../src/models/dependency/Dependency.js
   - [ ] 2 ../src/commands/verify.js
   - [ ] 2 ../src/commands/unlink.js
   - [ ] 2 ../src/commands/remove.js
   - [ ] 2 ../src/commands/push.js
   - [ ] 2 ../src/models/local/LocalLibController.js
   - [ ] 2 ../src/models/network/ControllerFor.js
   - [ ] 2 ../src/commands/publish.js
   - [ ] 2 ../src/commands/link.js
   - [ ] 2 ../src/models/network/NetworkLibController.js
   - [ ] 2 ../src/commands/init.js
   - [ ] 2 ../src/models/files/ZosNetworkFile.js
   - [ ] 2 ../src/commands/freeze.js
   - [ ] 2 ../src/scripts/freeze.js
   - [ ] 2 ../src/scripts/init-lib.js
   - [ ] 2 ../src/scripts/init.js
   - [ ] 2 ../src/scripts/link.js
   - [ ] 2 ../src/scripts/publish.js
   - [ ] 2 ../src/scripts/pull.js
   - [ ] 2 ../src/commands/check.js
   - [ ] 2 ../src/commands/bump.js
   - [ ] 2 ../src/scripts/unlink.js
   - [ ] 2 ../src/utils/runWithTruffle.js
   - [ ] 2 ../src/scripts/bump.js
   - [ ] 3 ../src/scripts/push.js
   - [ ] 3 ../src/scripts/update.js
   - [ ] 3 ../src/scripts/create.js
   - [ ] 3 ../src/models/local/LocalAppController.js
   - [ ] 3 ../src/commands/set-admin.js
   - [ ] 3 ../src/scripts/set-admin.js
   - [ ] 3 ../src/bin/program.js
   - [ ] 3 ../src/models/status/StatusChecker.js
   - [ ] 3 ../src/models/files/ZosPackageFile.js
   - [ ] 3 setup.js
   - [ ] 3 ../src/models/local/ControllerFor.js
   - [ ] 4 ../src/commands/add.js
   - [ ] 4 ../src/commands/create.js
   - [ ] 4 ../src/models/network/NetworkBaseController.js
   - [ ] 4 ../src/models/local/LocalBaseController.js
   - [ ] 4 ../src/commands/status.js
   - [ ] 4 ../src/commands/update.js
   - [ ] 5 ../src/models/network/NetworkAppController.js
   - [ ] 16 ../src/commands/index.js
   - [ ] 24 commands/share.js
</details>

&nbsp;
### Cli Phase 4: Typed dependencies

- [ ] packages/cli
  - [ ] axios
  - [ ] chalk
  - [ ] cheerio
  - [ ] commander
  - [ ] lockfile
  - [ ] lodash
  - [ ] npm-programmatic
  - [ ] semver
  - [ ] sinon
  - [ ] web3-provider-engine

### Cli Phase 5: Strict compiler and linter settings

This phase involves enabling stricter Typescript compiler settings and making all the necessary changes in the Typescript files. The documentation for all compiler settings can be found at http://www.typescriptlang.org/docs/handbook/compiler-options.html. The settings should be set in the following order:

#### Compiler settings
- [ ] maps: true // Activate source maps and, ideally, try out a debugging workflow.
- [ ] declaration: true // (not per package, but in the root tsconfig.json)
- [ ] esModuleInterop: false // Disable compatibility with Babel.
- [ ] checkJs: true // Report errors in `.js` files.
- [ ] alwaysStrict: true // Parse Javascript in strict mode.
- [ ] allowJs: false // Stop allowing `.js` files.
- [ ] noUnusedLocals: true // Report errors on unused locals.
- [ ] noUnusedParameters: true // Report errors on unused parameters.
- [ ] noImplicitReturns: true // Report error when not all code paths in function return a value.
- [ ] noImplicitThis: true // `this.` needs to be typed always.
- [ ] noImplicitAny: true // No inference of the `any` type.
- [ ] strictNullChecks: true // `null` and `undefined` are strict types, to be handled by unions.
- [ ] strictFuncitonTypes: true // Disable bivariant parameter checking for function types.
- [ ] strictPropertyInitialization: true // Ensure non-undefined class properties are initialized in the constructor.
- [ ] noEmitOnError: true // Do not output any Javascript if any error is found.

### Cli Phase 6: OOP enforcing

In this phase, we can begin focusing on refactors that make the code more OOP designed. This means not just complying to Typescript syntax, but actually architecturing the code around Classes, Interfases, Generics, etc. That is, making the most out of the OOP design patterns that Typescript enables.

*TBD: Define task list of refactors that enforce a more OOP-like architecture. Drawing an in depth UML diagram would help in identifying OOP structures that could be applied.

### Cli Phase 7: Cleanup

- [ ] Resolve all `TS-TODO` comments.
- [ ] Make sure that all common compiler settings are in the root tsconfig.json, and not on lib or cli.
- [ ] Invite frangio to the team.
- [ ] Drink beers :beers: .

### Further Phases

At this point, most of Lib and Cli should be ported to Typescript. However, most of the test code is still in Javascript. Next steps could be:
- [ ] Remove Truffle from the tests so that ts-node is no longer needed.
- [ ] Port all code from Js to Ts in the test folders of both lib and cli.
- [ ] Port the vouching package to Ts as well.

**Comment by facuspagnuolo** [comment]
Closing this issue
