### ISSUE TITLE
Support Solidity 0.5.x

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#514]
#### TODO
- [x] Do not use truffle-workflow-compile, but go to truffle via shell instead

- [x] Check if node_modules/bin/truffle exists, if so, call it
If not, try a global one
If not, let the user know they need a truffle

- [x] Check dependency from CLI on truffle
What happens if we remove it? Will the user be able to choose between 4 and 5? Declare as a dependency or as peer dependency? Watch out on installation guides that rely on npm install zos to get started.

- [x] Allow users to keep working on Solidity 0.4 if they wish to do so

Please review following https://github.com/zeppelinos/zos/commits/release/2.1.0
