### ISSUE TITLE
Publish docs for versions 2.1 and 2.2

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#635]
The latest version in docs is 2.0.0 and we have a few releases to the sources for versions 2.1 and 2.2. This issue is simply for tracking all the work related to this upgrade.

#### Make sure all guides work with zOS 2.1
- [x] Issue #639 "The quickstart guide from the documentation doesn't work with zOS v2.1.x" - Fixed by PR #643
- [x] Issue #656 "Programmatic usage guide needs to be updated for zOS 2.1" - Fixed by #658
- [x] Issue #655 "ERC20 Migration guide needs to be updated for zOS 2.1" - Fixed by #659

#### Document changes and new features
- [x] Delete or change notes like "The current version of ZeppelinOS uses Solidity 0.4.24..." - Fixed by #662
- [x] Document ability to use different Solidity compiler versions - Fixed by #662
- [x] Document contract verification on Etherscan - Fixed by PR #662
- [x] Re-generate dynamic docs
- [x] #566 Add note about upgrades among different compiler versions - Fixed by PR #662

#### Publish 2.1
- [x] Publish docs for version 2.1

#### Make sure all guides work with zOS 2.2
- [x] Migrate guides to use zOS 2.2 with Solidity 0.5, Truffle 5, Web3 1.0, async/await in truffle console, etc. - Fixed by #677

#### Document changes and new features
- [x] Remove mentions to transparent proxy. - Fixed by #686
- [x] Update section about transparent proxy. - Fixed by #686
- [x] Update contracts architecture section. - Fixed by #686
- [x] Update configuration files section. - Fixed by #686
- [x] Remove link to vouching contracts in vouching.md - Fixed by #690
- [x] #683 Add "Cannot call fallback function from the proxy admin" error to FAQ - Fixed by #690
- [x] #684 Add instructions on migration from 2.1 to 2.2 in documentation - Solved by #689

#### Publish 2.2
- [x] Publish docs for version 2.2

### Nice to haves
- [ ] #628 Link in documentation pointing to source are broken
- [x] #616 "Add hints on running migrations in contracts on upgrades in docs" - Fixed by PR #634
- [ ] #350 Consider renaming stake variable/methods to use 'vouch' instead
- [ ] #252 Doesn't work on windows 10
- [ ] #599 Outdated reference to BaseApp.sol in documentation
- [ ] #624 Deployment guide is unclear since it does not include creating a contract
- [ ] #372 Quickstart on the top bar should link to deploying
- [x] "spacial" as in spacex in writing_contracts.md - Fixed by PR #660
- [ ] #14 Add documentation for lib exported functions
- [ ] #149 Add documentation for CLI exported scripts
- [x] #339 Add guide to build an upgradeable ERC20
- [ ] #460 Create example project for creating upgradeable instances from a contract
