### ISSUE TITLE
Improvements on docs

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#696]
This issue comprises the list of nice to haves from #635

- [x] #628 Link in documentation pointing to source are broken - Fixed by https://github.com/OpenZeppelin/solidity-docgen/pull/19
- [x] #616 "Add hints on running migrations in contracts on upgrades in docs" - Fixed by PR #634
- [x] #350 Consider renaming stake variable/methods to use 'vouch' instead - n/a, not relevant to docs anymore - moved to the vouching repo https://github.com/zeppelinos/zos-vouching/issues/9
- [x] #599 Outdated reference to BaseApp.sol in documentation - Fixed #697
- [x] #624 Deployment guide is unclear since it does not include creating a contract - Fixed by #698 
- [x] #372 Quickstart on the top bar should link to deploying - CLOSED, see comments on issue
- [x] "spacial" as in spacex in writing_contracts.md - Fixed by PR #660 
- [x] #339 Add guide to build an upgradeable ERC20 - Done already with zos_lib.md in docs?
- [x] #460 Create example project for creating upgradeable instances from a contract - Fixed by #724
- [x] #726 Update section on calling initialize manually - Fixed by #728

**Comment by jcarpanelli** [comment]
Hey @ajsantander, just to be clear, remember that as we've already generated both `v2.1.0` and `v2.2.0` docs, you'll have to edit the already generated `.md`s in the folders `docs/docs/website/versioned_docs/version-2.1.0` and `docs/website/versioned_docs/version-2.2.0`. Also, you will have to update the `.md`s inside the `docs/docs/docs/` folder for `v2.2.0`.

**Comment by ajsantander** [comment]
@jcarpanelli yes I understand. 

We may choose to just leave these improvements for the next update instead. @spalladino what do you think?

**Comment by spalladino** [comment]
@ajsantander @jcarpanelli your call! If it's easy to incorporate the improvements on this version, then I'd say go for it.
